version: "3"

services:
  # в servicen описываются приложения. приложение web это - django devolepment сервер на которм и будет подыматься веб приложение
  web:

    # Ключевое слово "build" позволяет задать
    # путь к файлу Dockerfile, который нужно использовать для создания образа,
    # который позволит запустить сервис.
    build:
      #context определяет путь к каталогу, содержащему файл Dockerfile
      context: .

    #пробрасываем порты, соответственно 8000 порт в докер контейнере будет на 8000 порту в локальной ОС
    ports:
      - "8000:8000"

    #  Локальную папку src подключаем к папке src в докере.
    # Тк она подключенна то все изменеия которые мы будем производить в локальноый папке будут так же скопированны в папку в докере
    volumes:
      - ./src:/src

    # комманда для запуска сервера через shell
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"



