# Generated by Django 4.2.11 on 2024-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Название главы'),
        ),
    ]
