# Generated by Django 4.2.11 on 2024-03-31 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0006_composition_avg_rating_composition_count_bookmarks_and_more'),
        ('chapter', '0003_alter_page_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='composition.composition'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликована ли глава'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикациии'),
        ),
    ]
