# Generated by Django 4.2.11 on 2024-03-30 08:41

import api.v1.composition.services
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('composition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='composition',
            name='count_bookmarks',
            field=models.IntegerField(default=0, verbose_name='Количество в закладках у пользователей'),
        ),
        migrations.AddField(
            model_name='composition',
            name='count_rating',
            field=models.IntegerField(default=0, verbose_name='Количество голосов рейтинга'),
        ),
        migrations.AddField(
            model_name='composition',
            name='total_votes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков на всех главах'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='composition_image',
            field=models.ImageField(default='composition_image/default_composition_image.jpeg', upload_to=api.v1.composition.services.get_path_upload_title, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='composition',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usercompositionrelation',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_and_rating', to='composition.composition'),
        ),
        migrations.AlterField(
            model_name='usercompositionrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_and_rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
