# Generated by Django 4.2.11 on 2024-03-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0002_composition_avg_rating_composition_count_bookmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='count_bookmarks',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='count_rating',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='total_votes',
        ),
    ]
