# Generated by Django 4.2.11 on 2024-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0003_remove_composition_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
