# Generated by Django 4.2.11 on 2024-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0005_alter_composition_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='composition',
            name='count_bookmarks',
            field=models.IntegerField(default=0, verbose_name='Количество в закладках у пользователей'),
        ),
        migrations.AddField(
            model_name='composition',
            name='count_rating',
            field=models.IntegerField(default=0, verbose_name='Количество голосов рейтинга'),
        ),
        migrations.AddField(
            model_name='composition',
            name='total_votes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков на всех главах'),
        ),
    ]
