# Generated by Django 4.2.11 on 2024-03-28 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250, verbose_name='Текст сообщения')),
                ('created', models.DateTimeField(auto_now=True)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='composition.composition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
