# Generated by Django 4.2.11 on 2024-03-28 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterNotifications',
            new_name='UserChapterNotifications',
        ),
    ]
